
### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "example+2@example.com",
    "password": "123456"
}

### SignIn
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "example+2@example.com",
    "password": "123456"
}


### Find a particular user with a given ID
GET http://localhost:3000/auth/1


### Find all users with a given email
GET http://localhost:3000/auth?email=example@example.com